services:
  frostfire-forge-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frostfire-forge-dev:latest
    restart: on-failure
    ports:
      - "8080:8080"
      - "3001:3001"
    volumes:
      - ./.env.development:/app/.env.development:ro
    env_file:
      - .env.development
    networks:
      - frostfire-network-dev

networks:
  frostfire-network-dev:
    driver: bridge
