name: Build and Release (Development)

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: self-hosted
    environment: production
    steps:
      - name: Clean Up Files
        working-directory: .
        run: |
          cd ../../
          rm -rf Frostfire-Forge

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun Canary
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install Dependencies
        run: |
          bun install

      - name: Create Configuration
        run: |
          bun create-config

      - name: Setup SQLite Database
        run: |
          bun setup-development

      - name: Update environment variables
        run: |
          sed -i 's|localhost|forge.lillious.com|g' .env.development
